version: "3.9"

services:
  auth:
    build:
      context: .
      target: development
      args:
        - VERSION=18.12.1
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app

  maildev:
    image: maildev/maildev:2.0.5
    hostname: maildev
    ports:
      - 1025:1025
      - 1080:1080
